services:

  server:
    image: gitea/gitea:${GITEA_TAG:-1}
    restart: ${RESTART:-unless-stopped}
    logging:
      driver: ${LOGGING_DRIVER:-local}
    ports:
      - "${HTTP_PORT:-3000}:3000"
      - "${SSH_PORT:-222}:22"
    volumes:
      - ${GITEA_DATA_PATH:-server-data}:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file: .env
    environment:
      GITEA__database__DB_TYPE: postgres
      GITEA__database__HOST: db:5432
      GITEA__database__NAME: ${POSTGRES_DB:-gitea}
      GITEA__database__USER: ${POSTGRES_USER:-gitea}
      GITEA__database__PASSWD: ${POSTGRES_PASSWORD:-gitea}
    depends_on:
      - database

  database:
    image: postgres:${POSTGRES_TAG:-14}
    restart: ${RESTART:-unless-stopped}
    logging:
      driver: ${LOGGING_DRIVER:-local}
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-gitea}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-gitea}
      POSTGRES_DB: ${POSTGRES_DB:-gitea}
    volumes:
      - ${DB_DATA_PATH:-db-data}:/var/lib/postgresql/data

volumes:
  server-data:
  db-data: